# Generated by Django 5.1.4 on 2025-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mijoz', 'Mijoz'), ('buxgalter', 'Buxgalter'), ('admin', 'Admin')], default='mijoz', max_length=10),
        ),
    ]
