# Generated by Django 5.1.7 on 2025-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_report_report_type_report_report_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='accountant',
            name='specialty',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
